version: '3'
services:
  app:
    build: ./
    image: aboni/website
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    env_file: ./.env
    volumes:
      - ./nginx/templates:/etc/nginx/templates/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
