version: '3'
services:
  app:
    build: ./
    env_file: .env.local
    image: aboni/website
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=abonitech
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
